version: '2'
services:
 wp:
  image: wordpress:4.7
  ports:
   - 3000:80
  environment:
   - WORDPRESS_DB_PASSWORD=password
   - WORDPRESS_DB_HOST=db
  depends_on: 
   - db
 db:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=password
